---
- name: Create Docker compose directory
  file:
    path: "{{ webhook_compose_dir }}"
    state: directory

- name: Create Webhook data directory
  file:
    path: "{{ webhook_compose_dir }}/data"
    state: directory

- name: Create Webhook scripts directory
  file:
    path: "{{ webhook_compose_dir }}/data/scripts"
    state: directory

- name: Template Docker compose config
  template:
    src: "{{ item.src }}"
    dest: "{{ webhook_compose_dir }}/{{ item.dst }}"
    mode: 0644
  with_items:
    - { src: docker-compose.yml.j2, dst: docker-compose.yml }

- name: Template Webhook project scripts
  template:
    src: project_script.sh.j2
    dest: "{{ webhook_compose_dir }}/data/scripts/awx-project-{{ item.name }}.sh"
    mode: 0700
  with_items: "{{ webhook_awx_projects }}"
  notify: Enable Webhook

- name: Template Webhook job scripts
  template:
    src: job_script.sh.j2
    dest: "{{ webhook_compose_dir }}/data/scripts/awx-job-{{ item.name }}.sh"
    mode: 0700
  with_items: "{{ webhook_awx_jobs }}"
  notify: Enable Webhook

- name: Template Webhook certificate
  template:
    src: "{{ item.src }}"
    dest: "{{ webhook_compose_dir }}/data/{{ item.dst }}"
    mode: 0644
  with_items:
    - { src: cert.pem.j2, dst: cert.pem }
    - { src: cert.key.j2, dst: cert.key }
  notify: Enable Webhook

- name: Template Webhook config
  template:
    src: hooks.json.j2
    dest: "{{ webhook_compose_dir }}/data/hooks.json"
  notify: Enable Webhook
